# Generated by Django 5.1.4 on 2025-01-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="memo",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
