# Generated by Django 5.1.4 on 2025-01-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0002_transaction_memo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
