# Generated by Django 5.1.4 on 2025-01-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0004_alter_transaction_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="memo",
            field=models.TextField(blank=True, null=True),
        ),
    ]
